
// USAURIOS
export const CREAR_USUARIO = 'CREAR_USUARIO';
export const TRAER_USUARIO = 'TRAER_USUARIO';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO'
 
